-- Month-end lock/approval workflow for the Detailed Timesheet screen: employee "locks" a month
-- (submits), a manager then approves or rejects it. One row per (user, year, month).
-- "year"/"month" quoted — both are reserved words in H2 (bit us before on a different table).
CREATE TABLE attendance_month_lock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    "year" INT NOT NULL,
    "month" INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    submitted_at TIMESTAMP,
    approved_by BIGINT,
    approved_at TIMESTAMP,
    rejection_reason VARCHAR(500),
    CONSTRAINT fk_month_lock_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_month_lock_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT uq_month_lock_user_period UNIQUE (user_id, "year", "month")
);
